### ISSUE TITLE
Plugin usage

### ISSUE THREAD

**Issue by kalimeroo** [T0T0R/BlenderCIF#1]
Could you please document on how to use this plugin ?
I did a manual installation under user preferences but the plugin does not appear in the plugin list.

Regards

**Comment by T0T0R** [comment]
Thank you @kalimeroo for your interest.
I took a break from the development of this plugin because of license concerns with my employer.
But I intend to resume the development at some point, and to finish it.

**Comment by kalimeroo** [comment]
Thanks for the feedback.
